
services:
  db-go:
    image: postgres:15
    container_name: traffic_db_go
    environment:
      - POSTGRES_USER=go_user
      - POSTGRES_PASSWORD=go_pass
      - POSTGRES_DB=go_db
    ports:
      - "5420:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: traffic_app_go
    ports:
      - "8080:8080"
    depends_on:
      - db-go
    environment:
      - DSN=host=db-go user=go_user password=go_pass dbname=go_db port=5432 sslmode=disable TimeZone=UTC
      

volumes:
  db_data: