package domain

import (
	"time"
)

// Alert represents a security alert generated by the system
type Alert struct {
	ID              uint
	RuleID          uint
	Rule            *Rule
	SecurityEventID uint
	Timestamp       time.Time
	Severity        EventSeverity
	Status          AlertStatus
	AssignedTo      *uint
	Resolution      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// IsValid validates the alert's basic properties
func (a *Alert) IsValid() bool {
	return a.RuleID != 0 && a.SecurityEventID != 0 && a.Severity != "" && a.Status != ""
}

// CanTransitionToStatus checks if the alert can transition to the given status
func (a *Alert) CanTransitionToStatus(newStatus AlertStatus) bool {
	// Implement state transition rules
	// For example, a closed alert might not be reopened
	if a.Status == AlertStatusClosed && newStatus == AlertStatusOpen {
		return false
	}
	return true
}

// IsAssignableToUser checks if the alert can be assigned to a user
func (a *Alert) IsAssignableToUser(userID uint) bool {
	// Add business logic for assignment rules if needed
	return true
}