version: '3.9'


services:
  db:
    image: postgres:15
    container_name: traffic_db
    environment:
      - POSTGRES_USER=traffic_user
      - POSTGRES_PASSWORD=traffic_pass
      - POSTGRES_DB=traffic_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  api:
    build: .
    container_name: traffic_api
    ports:
      - "8900:8900"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://traffic_user:traffic_pass@db:5432/traffic_db
    volumes:
      - ./app:/app/app
      

  test:
    build: .
    container_name: traffic_test
    depends_on:
      - db
    environment:
    - "DATABASE_URL=sqlite:///:memory:?check_same_thread=False?cache=shared"
    - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: pytest



volumes:
  db_data:
