

services:
  db:
    image: postgres:15
    container_name: traffic_db
    environment:
      - POSTGRES_USER=traffic_user
      - POSTGRES_PASSWORD=traffic_pass
      - POSTGRES_DB=traffic_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  api:
    build: .
    container_name: traffic_api
    ports:
      - "8900:8900"
    depends_on:
      - kafka
      - db
    environment:
      - DATABASE_URL=postgresql://traffic_user:traffic_pass@db:5432/traffic_db
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      

  test:
    build: .
    container_name: traffic_test
    depends_on:
      - db
      - kafka
    env_file:
     - ./envs/.env.test
    environment:
    - "DATABASE_URL=sqlite:///:memory:?check_same_thread=False&cache=shared"
    - PYTHONPATH=/app
    - PYTEST_ADDOPTS="-v"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    entrypoint: []  # Correctly override ENTRYPOINT to prevent running entrypoint.sh
    command: ["pytest", "/app/tests/"]  # Directly run pytest with options from PYTEST_ADDOPTS
  
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2182
  




volumes:
  db_data:
